/*
 * Pathwayos API
 *
 * Pathwayos API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CoursePathwaySequenceResponseCourseData : IEquatable<CoursePathwaySequenceResponseCourseData>
    {
        /// <summary>
        /// Gets or Sets Course
        /// </summary>
        [Required]
        [DataMember(Name="course", EmitDefaultValue=false)]
        public CourseDTO Course { get; set; }

        /// <summary>
        /// Gets or Sets CoursePathway
        /// </summary>
        [Required]
        [DataMember(Name="coursePathway", EmitDefaultValue=false)]
        public CoursePathwaySequenceDTO CoursePathway { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CoursePathwaySequenceResponseCourseData {\n");
            sb.Append("  Course: ").Append(Course).Append("\n");
            sb.Append("  CoursePathway: ").Append(CoursePathway).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CoursePathwaySequenceResponseCourseData)obj);
        }

        /// <summary>
        /// Returns true if CoursePathwaySequenceResponseCourseData instances are equal
        /// </summary>
        /// <param name="other">Instance of CoursePathwaySequenceResponseCourseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CoursePathwaySequenceResponseCourseData other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Course == other.Course ||
                    Course != null &&
                    Course.Equals(other.Course)
                ) && 
                (
                    CoursePathway == other.CoursePathway ||
                    CoursePathway != null &&
                    CoursePathway.Equals(other.CoursePathway)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Course != null)
                    hashCode = hashCode * 59 + Course.GetHashCode();
                    if (CoursePathway != null)
                    hashCode = hashCode * 59 + CoursePathway.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CoursePathwaySequenceResponseCourseData left, CoursePathwaySequenceResponseCourseData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CoursePathwaySequenceResponseCourseData left, CoursePathwaySequenceResponseCourseData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
