/*
 * Pathwayos API
 *
 * Pathwayos API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ExternalDirectFormResponse : IEquatable<ExternalDirectFormResponse>
    {
        /// <summary>
        /// Gets or Sets IsComplete
        /// </summary>
        [Required]
        [DataMember(Name="isComplete", EmitDefaultValue=true)]
        public bool IsComplete { get; set; }

        /// <summary>
        /// Gets or Sets FormResponse
        /// </summary>
        [Required]
        [DataMember(Name="formResponse", EmitDefaultValue=false)]
        public FormResponse FormResponse { get; set; }

        /// <summary>
        /// Gets or Sets IsRejectable
        /// </summary>
        [Required]
        [DataMember(Name="isRejectable", EmitDefaultValue=true)]
        public bool IsRejectable { get; set; }

        /// <summary>
        /// Gets or Sets SubmissionResponse
        /// </summary>
        [DataMember(Name="submissionResponse", EmitDefaultValue=false)]
        public FormSubmissionResponse SubmissionResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExternalDirectFormResponse {\n");
            sb.Append("  IsComplete: ").Append(IsComplete).Append("\n");
            sb.Append("  FormResponse: ").Append(FormResponse).Append("\n");
            sb.Append("  IsRejectable: ").Append(IsRejectable).Append("\n");
            sb.Append("  SubmissionResponse: ").Append(SubmissionResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ExternalDirectFormResponse)obj);
        }

        /// <summary>
        /// Returns true if ExternalDirectFormResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ExternalDirectFormResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExternalDirectFormResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    IsComplete == other.IsComplete ||
                    
                    IsComplete.Equals(other.IsComplete)
                ) && 
                (
                    FormResponse == other.FormResponse ||
                    FormResponse != null &&
                    FormResponse.Equals(other.FormResponse)
                ) && 
                (
                    IsRejectable == other.IsRejectable ||
                    
                    IsRejectable.Equals(other.IsRejectable)
                ) && 
                (
                    SubmissionResponse == other.SubmissionResponse ||
                    SubmissionResponse != null &&
                    SubmissionResponse.Equals(other.SubmissionResponse)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + IsComplete.GetHashCode();
                    if (FormResponse != null)
                    hashCode = hashCode * 59 + FormResponse.GetHashCode();
                    
                    hashCode = hashCode * 59 + IsRejectable.GetHashCode();
                    if (SubmissionResponse != null)
                    hashCode = hashCode * 59 + SubmissionResponse.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ExternalDirectFormResponse left, ExternalDirectFormResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ExternalDirectFormResponse left, ExternalDirectFormResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
