/*
 * Pathwayos API
 *
 * Pathwayos API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ServiceEventVerificationRequest : IEquatable<ServiceEventVerificationRequest>
    {
        /// <summary>
        /// Gets or Sets Days
        /// </summary>
        [DataMember(Name="days", EmitDefaultValue=true)]
        public List<ServiceEventVerificationRequestDay> Days { get; set; }

        /// <summary>
        /// Gets or Sets TotalHours
        /// </summary>
        [DataMember(Name="totalHours", EmitDefaultValue=true)]
        public double? TotalHours { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceEventVerificationRequest {\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  TotalHours: ").Append(TotalHours).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ServiceEventVerificationRequest)obj);
        }

        /// <summary>
        /// Returns true if ServiceEventVerificationRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ServiceEventVerificationRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceEventVerificationRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Days == other.Days ||
                    Days != null &&
                    other.Days != null &&
                    Days.SequenceEqual(other.Days)
                ) && 
                (
                    TotalHours == other.TotalHours ||
                    TotalHours != null &&
                    TotalHours.Equals(other.TotalHours)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Days != null)
                    hashCode = hashCode * 59 + Days.GetHashCode();
                    if (TotalHours != null)
                    hashCode = hashCode * 59 + TotalHours.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ServiceEventVerificationRequest left, ServiceEventVerificationRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ServiceEventVerificationRequest left, ServiceEventVerificationRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
