/*
 * Pathwayos API
 *
 * Pathwayos API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ServiceGroupControllerRemoveMembersRequest : IEquatable<ServiceGroupControllerRemoveMembersRequest>
    {
        /// <summary>
        /// Gets or Sets UserIds
        /// </summary>
        [Required]
        [DataMember(Name="userIds", EmitDefaultValue=false)]
        public List<long> UserIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceGroupControllerRemoveMembersRequest {\n");
            sb.Append("  UserIds: ").Append(UserIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ServiceGroupControllerRemoveMembersRequest)obj);
        }

        /// <summary>
        /// Returns true if ServiceGroupControllerRemoveMembersRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ServiceGroupControllerRemoveMembersRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceGroupControllerRemoveMembersRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    UserIds == other.UserIds ||
                    UserIds != null &&
                    other.UserIds != null &&
                    UserIds.SequenceEqual(other.UserIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (UserIds != null)
                    hashCode = hashCode * 59 + UserIds.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ServiceGroupControllerRemoveMembersRequest left, ServiceGroupControllerRemoveMembersRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ServiceGroupControllerRemoveMembersRequest left, ServiceGroupControllerRemoveMembersRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
