/*
 * Pathwayos API
 *
 * Pathwayos API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdateCategoriesRequests : IEquatable<UpdateCategoriesRequests>
    {
        /// <summary>
        /// Gets or Sets Activities
        /// </summary>
        [Required]
        [DataMember(Name="activities", EmitDefaultValue=false)]
        public List<long> Activities { get; set; }

        /// <summary>
        /// Gets or Sets Categories
        /// </summary>
        [Required]
        [DataMember(Name="categories", EmitDefaultValue=false)]
        public List<long> Categories { get; set; }

        /// <summary>
        /// Gets or Sets Forms
        /// </summary>
        [Required]
        [DataMember(Name="forms", EmitDefaultValue=false)]
        public List<long> Forms { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateCategoriesRequests {\n");
            sb.Append("  Activities: ").Append(Activities).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  Forms: ").Append(Forms).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdateCategoriesRequests)obj);
        }

        /// <summary>
        /// Returns true if UpdateCategoriesRequests instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateCategoriesRequests to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateCategoriesRequests other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Activities == other.Activities ||
                    Activities != null &&
                    other.Activities != null &&
                    Activities.SequenceEqual(other.Activities)
                ) && 
                (
                    Categories == other.Categories ||
                    Categories != null &&
                    other.Categories != null &&
                    Categories.SequenceEqual(other.Categories)
                ) && 
                (
                    Forms == other.Forms ||
                    Forms != null &&
                    other.Forms != null &&
                    Forms.SequenceEqual(other.Forms)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Activities != null)
                    hashCode = hashCode * 59 + Activities.GetHashCode();
                    if (Categories != null)
                    hashCode = hashCode * 59 + Categories.GetHashCode();
                    if (Forms != null)
                    hashCode = hashCode * 59 + Forms.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdateCategoriesRequests left, UpdateCategoriesRequests right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdateCategoriesRequests left, UpdateCategoriesRequests right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
