/*
 * Pathwayos API
 *
 * Pathwayos API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UserWorkflowStatusPotentialSignerDetails : IEquatable<UserWorkflowStatusPotentialSignerDetails>
    {
        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name="role", EmitDefaultValue=true)]
        public string Role { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public long Status { get; set; }

        /// <summary>
        /// Gets or Sets Responsibility
        /// </summary>
        [DataMember(Name="responsibility", EmitDefaultValue=true)]
        public long? Responsibility { get; set; }

        /// <summary>
        /// Gets or Sets SigningOrder
        /// </summary>
        [DataMember(Name="signingOrder", EmitDefaultValue=true)]
        public long? SigningOrder { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public long Type { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowFormSignatureId
        /// </summary>
        [DataMember(Name="workflowFormSignatureId", EmitDefaultValue=true)]
        public long? WorkflowFormSignatureId { get; set; }

        /// <summary>
        /// Gets or Sets Organization
        /// </summary>
        [DataMember(Name="organization", EmitDefaultValue=true)]
        public string Organization { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserWorkflowStatusPotentialSignerDetails {\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Responsibility: ").Append(Responsibility).Append("\n");
            sb.Append("  SigningOrder: ").Append(SigningOrder).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  WorkflowFormSignatureId: ").Append(WorkflowFormSignatureId).Append("\n");
            sb.Append("  Organization: ").Append(Organization).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UserWorkflowStatusPotentialSignerDetails)obj);
        }

        /// <summary>
        /// Returns true if UserWorkflowStatusPotentialSignerDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of UserWorkflowStatusPotentialSignerDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserWorkflowStatusPotentialSignerDetails other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Role == other.Role ||
                    Role != null &&
                    Role.Equals(other.Role)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                ) && 
                (
                    Responsibility == other.Responsibility ||
                    Responsibility != null &&
                    Responsibility.Equals(other.Responsibility)
                ) && 
                (
                    SigningOrder == other.SigningOrder ||
                    SigningOrder != null &&
                    SigningOrder.Equals(other.SigningOrder)
                ) && 
                (
                    Type == other.Type ||
                    
                    Type.Equals(other.Type)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    WorkflowFormSignatureId == other.WorkflowFormSignatureId ||
                    WorkflowFormSignatureId != null &&
                    WorkflowFormSignatureId.Equals(other.WorkflowFormSignatureId)
                ) && 
                (
                    Organization == other.Organization ||
                    Organization != null &&
                    Organization.Equals(other.Organization)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Role != null)
                    hashCode = hashCode * 59 + Role.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Responsibility != null)
                    hashCode = hashCode * 59 + Responsibility.GetHashCode();
                    if (SigningOrder != null)
                    hashCode = hashCode * 59 + SigningOrder.GetHashCode();
                    
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (WorkflowFormSignatureId != null)
                    hashCode = hashCode * 59 + WorkflowFormSignatureId.GetHashCode();
                    if (Organization != null)
                    hashCode = hashCode * 59 + Organization.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UserWorkflowStatusPotentialSignerDetails left, UserWorkflowStatusPotentialSignerDetails right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UserWorkflowStatusPotentialSignerDetails left, UserWorkflowStatusPotentialSignerDetails right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
