/*
 * Pathwayos API
 *
 * Pathwayos API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CheckPointApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>GET /CheckPoint/api/consumer/v1/checkpoint/:badges</remarks>
        [HttpGet]
        [Route("/CheckPoint/api/consumer/v1/checkpoint/{badges}")]
        [ValidateModelState]
        [SwaggerOperation("CheckPointApiConsumerV1CheckpointBadgesGet")]
        public virtual IActionResult CheckPointApiConsumerV1CheckpointBadgesGet()
        {


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>POST /CheckPoint/api/consumer/v1/checkpoint/:badges</remarks>
        [HttpPost]
        [Route("/CheckPoint/api/consumer/v1/checkpoint/{badges}")]
        [ValidateModelState]
        [SwaggerOperation("CheckPointApiConsumerV1CheckpointBadgesPost")]
        public virtual IActionResult CheckPointApiConsumerV1CheckpointBadgesPost()
        {


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>DELETE /CheckPoint/api/consumer/v1/checkpoint/:checkpoints</remarks>
        [HttpDelete]
        [Route("/CheckPoint/api/consumer/v1/checkpoint/{checkpoints}")]
        [ValidateModelState]
        [SwaggerOperation("CheckPointApiConsumerV1CheckpointCheckpointsDelete")]
        public virtual IActionResult CheckPointApiConsumerV1CheckpointCheckpointsDelete()
        {


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>PATCH /CheckPoint/api/consumer/v1/checkpoint/:checkpoints</remarks>
        [HttpPatch]
        [Route("/CheckPoint/api/consumer/v1/checkpoint/{checkpoints}")]
        [ValidateModelState]
        [SwaggerOperation("CheckPointApiConsumerV1CheckpointCheckpointsPatch")]
        public virtual IActionResult CheckPointApiConsumerV1CheckpointCheckpointsPatch()
        {


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>GET /CheckPoint/api/consumer/v1/off-track-report</remarks>
        [HttpGet]
        [Route("/CheckPoint/api/consumer/v1/off-track-report")]
        [ValidateModelState]
        [SwaggerOperation("CheckPointApiConsumerV1OffTrackReportGet")]
        public virtual IActionResult CheckPointApiConsumerV1OffTrackReportGet()
        {


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>PATCH /CheckPoint/api/consumer/v1/off-track-report/:off_track_report/dismiss</remarks>
        [HttpPatch]
        [Route("/CheckPoint/api/consumer/v1/off-track-report/{off_track_report}/dismiss")]
        [ValidateModelState]
        [SwaggerOperation("CheckPointApiConsumerV1OffTrackReportOffTrackReportDismissPatch")]
        public virtual IActionResult CheckPointApiConsumerV1OffTrackReportOffTrackReportDismissPatch()
        {


            throw new NotImplementedException();
        }
    }
}
